// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// doEM
List doEM(arma::vec y, arma::mat W, int L, arma::vec phi, arma::mat p, arma::vec rho, double gamma, double beta);
RcppExport SEXP _BERMUDA_doEM(SEXP ySEXP, SEXP WSEXP, SEXP LSEXP, SEXP phiSEXP, SEXP pSEXP, SEXP rhoSEXP, SEXP gammaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(doEM(y, W, L, phi, p, rho, gamma, beta));
    return rcpp_result_gen;
END_RCPP
}
// doPred
arma::vec doPred(arma::mat W, int L, arma::vec phi, arma::mat p, arma::vec rho);
RcppExport SEXP _BERMUDA_doPred(SEXP WSEXP, SEXP LSEXP, SEXP phiSEXP, SEXP pSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(doPred(W, L, phi, p, rho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BERMUDA_doEM", (DL_FUNC) &_BERMUDA_doEM, 8},
    {"_BERMUDA_doPred", (DL_FUNC) &_BERMUDA_doPred, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_BERMUDA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
